import Groq from "groq-sdk";
import fs from "fs";
import path from "path";
import dotenv from "dotenv";

dotenv.config();

const groq = new Groq({
  apiKey: process.env.GROQ_API_KEY,
});

const MODEL = process.env.MODEL || "llama-3.3-70b-versatile";
const MAX_TOKENS = parseInt(process.env.MAX_TOKENS) || 1000;
const OUTPUT_DIR = process.env.OUTPUT_DIR || "./generated";

// Ensure output directory exists
if (!fs.existsSync(OUTPUT_DIR)) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

async function generateScript(episode) {
  const prompt = `Generate a 4-minute YouTube video script for a cybersecurity & AI educational channel.

EPISODE DETAILS:
- Title: "${episode.title}"
- Keywords: ${episode.keywords.join(", ")}
- Difficulty: ${episode.difficulty}
- Cloudflare Relevant: ${episode.cloudflare_relevant}
${episode.cloudflare_products.length > 0 ? `- Cloudflare Products: ${episode.cloudflare_products.join(", ")}` : ""}
- Viral Angle: "${episode.viral_angle}"
- CTA: "${episode.cta}"

REQUIREMENTS:
1. **Duration**: Exactly 600-800 characters (approximately 3-4 minutes narration at natural speaking pace)
2. **Structure**:
   - Hook (10 sec): Grab attention with the viral angle
   - Introduction (30 sec): What we'll cover
   - Main Content (2-2.5 min): Explain concept simply (no jargon, use analogies)
   - Examples/Demo (30 sec): Real-world example or quick demo
   - CTA (30 sec): Call to action from episode details
3. **Tone**: Educational, accessible, conversational (think Elements of AI style)
4. **Language**: Spanish (Spain/Latinoamérica neutral)
5. **Accessibility**: Assume beginner audience for difficulty="${episode.difficulty}"
6. **Avoid**: 
   - Mentioning specific companies (banks, telcos, enterprises by name)
   - Code snippets (only describe concepts)
   - Too much jargon

RETURN FORMAT (JSON):
{
  "title": "${episode.title}",
  "script": "[Your 600-800 character script here]",
  "character_count": [exact count],
  "estimated_duration": "[3-4 minutes]",
  "keywords": [extracted keywords],
  "metadata": {
    "difficulty": "${episode.difficulty}",
    "cloudflare_relevant": ${episode.cloudflare_relevant},
    "episode_number": ${episode.episode}
  }
}

Generate the script now:`;

  try {
    const message = await groq.messages.create({
      model: MODEL,
      max_tokens: MAX_TOKENS,
      messages: [
        {
          role: "user",
          content: prompt,
        },
      ],
    });

    const content = message.content[0].text;

    // Parse JSON response
    const jsonMatch = content.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error("Invalid JSON response from Groq");
    }

    const result = JSON.parse(jsonMatch[0]);

    // Validate character count
    if (result.character_count < 600 || result.character_count > 800) {
      console.warn(
        `⚠️  Warning: Script for episode ${episode.episode} is ${result.character_count} chars (target: 600-800)`
      );
    }

    return result;
  } catch (error) {
    console.error(`❌ Error generating script for episode ${episode.episode}:`, error.message);
    return null;
  }
}

async function saveScript(episode, scriptData) {
  if (!scriptData) return;

  const filename = `week-${String(episode.week).padStart(2, "0")}-episode-${String(episode.episode).padStart(2, "0")}.md`;
  const filepath = path.join(OUTPUT_DIR, filename);

  const markdown = `# ${scriptData.title}

**Episode**: ${episode.episode}  
**Week**: ${episode.week}  
**Difficulty**: ${episode.difficulty}  
**Duration**: ${scriptData.estimated_duration}  
**Characters**: ${scriptData.character_count}  

## Keywords
${scriptData.keywords.map((k) => `- ${k}`).join("\n")}

## Script

${scriptData.script}

## Metadata
- Cloudflare Relevant: ${scriptData.metadata.cloudflare_relevant}
- Products: ${episode.cloudflare_products.join(", ") || "N/A"}
- CTA: ${episode.cta}
- Viral Angle: ${episode.viral_angle}

---
*Generated by JOVI Academy Script Generator*
`;

  fs.writeFileSync(filepath, markdown);
  console.log(`✅ Saved: ${filename}`);
}

async function generateBatch(episodes) {
  console.log(`\n🎬 Generating ${episodes.length} scripts...`);
  console.log(`📁 Output directory: ${OUTPUT_DIR}\n`);

  const results = {
    total: episodes.length,
    success: 0,
    failed: 0,
    scripts: [],
  };

  for (const episode of episodes) {
    process.stdout.write(`[${episode.week}-${episode.episode}] Generating...`);

    const scriptData = await generateScript(episode);

    if (scriptData) {
      await saveScript(episode, scriptData);
      results.success++;
      results.scripts.push({
        episode: episode.episode,
        week: episode.week,
        title: scriptData.title,
        characters: scriptData.character_count,
      });

      // Small delay to avoid rate limiting
      await new Promise((resolve) => setTimeout(resolve, 1000));
    } else {
      results.failed++;
      console.log(" ❌ Failed");
    }
  }

  // Save summary
  const summary = {
    generated_at: new Date().toISOString(),
    total: results.total,
    success: results.success,
    failed: results.failed,
    scripts: results.scripts,
  };

  fs.writeFileSync(
    path.join(OUTPUT_DIR, "index.json"),
    JSON.stringify(summary, null, 2)
  );

  console.log(`\n📊 Summary:`);
  console.log(`   ✅ Success: ${results.success}/${results.total}`);
  console.log(`   ❌ Failed: ${results.failed}/${results.total}`);
  console.log(`   📄 Index saved: ${OUTPUT_DIR}/index.json`);

  return results;
}

// Main execution
async function main() {
  try {
    // Load curriculum
    const curriculumPath =
      process.env.CURRICULUM_PATH ||
      "../../curriculum/2026-q1.json";

    if (!fs.existsSync(curriculumPath)) {
      console.error(`❌ Curriculum not found at ${curriculumPath}`);
      process.exit(1);
    }

    const curriculum = JSON.parse(fs.readFileSync(curriculumPath, "utf-8"));

    // Extract all episodes
    const allEpisodes = [];
    curriculum.episodes.forEach((week) => {
      week.episodes.forEach((episode) => {
        allEpisodes.push({
          ...episode,
          week: week.week,
        });
      });
    });

    console.log(`\n🎯 JOVI Academy Script Generator`);
    console.log(`📚 Curriculum: Q${curriculum.quarter} ${curriculum.year}`);
    console.log(
      `📖 Total episodes available: ${allEpisodes.length}\n`
    );

    // Generate batch
    const batchSize =
      parseInt(process.env.BATCH_SIZE) || allEpisodes.length;
    const episodesToGenerate = allEpisodes.slice(
      0,
      Math.min(batchSize, allEpisodes.length)
    );

    await generateBatch(episodesToGenerate);
  } catch (error) {
    console.error("Fatal error:", error);
    process.exit(1);
  }
}

main();
